Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/jammy64"

  # APP SERVER
  config.vm.define "app01" do |app|
    app.vm.hostname = "app01"
    app.vm.network "private_network", ip: "192.168.56.11"

    app.vm.provider "virtualbox" do |vb|
      vb.memory = "2048"
      vb.cpus = 2
    end
  end

  # DATABASE SERVER
  config.vm.define "db01" do |db|
    db.vm.hostname = "db01"
    db.vm.network "private_network", ip: "192.168.56.12"

    db.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = 1
    end
  end

  # RABBITMQ SERVER
  config.vm.define "rmq01" do |rmq|
    rmq.vm.hostname = "rmq01"
    rmq.vm.network "private_network", ip: "192.168.56.13"

    rmq.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = 1
    end
  end

  # MEMCACHED SERVER
  config.vm.define "mc01" do |mc|
    mc.vm.hostname = "mc01"
    mc.vm.network "private_network", ip: "192.168.56.14"

    mc.vm.provider "virtualbox" do |vb|
      vb.memory = "512"
      vb.cpus = 1
    end
  end

  # NGINX SERVER
  config.vm.define "nginx01" do |nginx|
    nginx.vm.hostname = "nginx01"
    nginx.vm.network "private_network", ip: "192.168.56.15"

    nginx.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = 1
    end
  end

end
